#!/usr/bin/env python3
"""
generate_profile.py - Generate profiled kernel files with arithmetic operation counting

This script parses a C++ kernel file and generates a *_profile.cpp version that
counts arithmetic operations (+, -, *, /, exp, log, sqrt, pow, etc.)

Usage:
    python3 generate_profile.py <input_file.cpp> [output_file.cpp]
    
Example:
    python3 generate_profile.py inner_product_compute.cpp
    python3 generate_profile.py inner_product_compute.cpp inner_product_compute_profile.cpp
"""

import re
import sys
import os
from pathlib import Path

# Arithmetic operations to track
BINARY_OPS = {
    '+': 'arith_add',
    '-': 'arith_sub',
    '*': 'arith_mul',
    '/': 'arith_div',
}

# Compound assignment operators
COMPOUND_OPS = {
    '+=': 'arith_add',
    '-=': 'arith_sub',
    '*=': 'arith_mul',
    '/=': 'arith_div',
}

# Math functions to track
MATH_FUNCTIONS = {
    'exp': 'arith_exp',
    'expf': 'arith_exp',
    'log': 'arith_log',
    'logf': 'arith_log',
    'log2': 'arith_log',
    'log2f': 'arith_log',
    'log10': 'arith_log',
    'log10f': 'arith_log',
    'sqrt': 'arith_sqrt',
    'sqrtf': 'arith_sqrt',
    'pow': 'arith_pow',
    'powf': 'arith_pow',
    'sin': 'arith_trig',
    'sinf': 'arith_trig',
    'cos': 'arith_trig',
    'cosf': 'arith_trig',
    'tan': 'arith_trig',
    'tanf': 'arith_trig',
    'abs': 'arith_other',
    'fabs': 'arith_other',
    'fabsf': 'arith_other',
    'floor': 'arith_other',
    'floorf': 'arith_other',
    'ceil': 'arith_other',
    'ceilf': 'arith_other',
    'round': 'arith_other',
    'roundf': 'arith_other',
    'fma': 'arith_fma',
    'fmaf': 'arith_fma',
}

PROFILE_HEADER = '''/**
 * @file {filename}
 * @brief Profiled implementation with arithmetic operation counting
 * 
 * AUTO-GENERATED FILE - Do not edit manually.
 * Generated by generate_profile.py
 * 
 * This file counts arithmetic operations:
 * - ADD, SUB, MUL, DIV
 * - EXP, LOG, SQRT, POW, TRIG
 * - FMA (fused multiply-add)
 * - OTHER (abs, floor, ceil, round, etc.)
 */

{includes}
#include <cstdint>
#include <iostream>

namespace heteromm {{
namespace step {{

// Global counters for profiling arithmetic operations
struct ArithProfileCounters {{
    uint64_t arith_add = 0;      // Addition operations (+, +=)
    uint64_t arith_sub = 0;      // Subtraction operations (-, -=)
    uint64_t arith_mul = 0;      // Multiplication operations (*, *=)
    uint64_t arith_div = 0;      // Division operations (/, /=)
    uint64_t arith_exp = 0;      // Exponential operations (exp, expf)
    uint64_t arith_log = 0;      // Logarithm operations (log, log2, log10)
    uint64_t arith_sqrt = 0;     // Square root operations (sqrt, sqrtf)
    uint64_t arith_pow = 0;      // Power operations (pow, powf)
    uint64_t arith_trig = 0;     // Trigonometric operations (sin, cos, tan)
    uint64_t arith_fma = 0;      // Fused multiply-add operations
    uint64_t arith_other = 0;    // Other arithmetic (abs, floor, ceil, round)
    
    void reset() {{
        arith_add = arith_sub = arith_mul = arith_div = 0;
        arith_exp = arith_log = arith_sqrt = arith_pow = 0;
        arith_trig = arith_fma = arith_other = 0;
    }}
    
    uint64_t total() const {{
        return arith_add + arith_sub + arith_mul + arith_div + 
               arith_exp + arith_log + arith_sqrt + arith_pow +
               arith_trig + arith_fma + arith_other;
    }}
    
    void print() const {{
        std::clog << "========== ARITHMETIC PROFILE RESULTS ==========" << std::endl;
        std::clog << "  ADD:   " << arith_add << std::endl;
        std::clog << "  SUB:   " << arith_sub << std::endl;
        std::clog << "  MUL:   " << arith_mul << std::endl;
        std::clog << "  DIV:   " << arith_div << std::endl;
        std::clog << "  EXP:   " << arith_exp << std::endl;
        std::clog << "  LOG:   " << arith_log << std::endl;
        std::clog << "  SQRT:  " << arith_sqrt << std::endl;
        std::clog << "  POW:   " << arith_pow << std::endl;
        std::clog << "  TRIG:  " << arith_trig << std::endl;
        std::clog << "  FMA:   " << arith_fma << std::endl;
        std::clog << "  OTHER: " << arith_other << std::endl;
        std::clog << "  ----------------------------------------" << std::endl;
        std::clog << "  TOTAL: " << total() << std::endl;
        std::clog << "=================================================" << std::endl;
    }}
}};

// Global profile counter instance
static ArithProfileCounters g_arith_profile;

'''

PROFILE_FOOTER = '''
}  // namespace step
}  // namespace heteromm
'''


def count_binary_ops(line: str) -> dict:
    """Count binary arithmetic operations in a line of code."""
    counts = {v: 0 for v in BINARY_OPS.values()}
    
    # Skip comments
    if line.strip().startswith('//'):
        return counts
    
    # Remove string literals to avoid false positives
    line = re.sub(r'"[^"]*"', '', line)
    line = re.sub(r"'[^']*'", '', line)
    
    # First handle compound operators (must be done before simple operators)
    for op, counter in COMPOUND_OPS.items():
        count = line.count(op)
        counts[counter] += count
        # Remove compound ops to avoid double counting
        line = line.replace(op, '  ')
    
    # Now count simple binary operators
    # We need to be careful with:
    # - Pointer operators (* for dereference, -> for member access)
    # - Unary operators (++, --, unary - and +)
    # - Comments (//)
    
    # Remove pointer/reference operators and increments
    line = re.sub(r'->', '  ', line)  # member access
    line = re.sub(r'\+\+', '  ', line)  # increment
    line = re.sub(r'--', '  ', line)  # decrement
    
    # Count remaining operators
    # For *, we try to distinguish multiplication from dereference/pointer
    # Multiplication typically has operands on both sides
    for op, counter in BINARY_OPS.items():
        if op == '*':
            # Match multiplication: something * something
            # Avoid matching pointer declarations like "float*" or dereference "*ptr"
            matches = re.findall(r'[\w\)\]]\s*\*\s*[\w\(\[]', line)
            counts[counter] += len(matches)
        elif op == '-':
            # Match subtraction, avoid unary minus
            matches = re.findall(r'[\w\)\]]\s*-\s*[\w\(\[]', line)
            counts[counter] += len(matches)
        elif op == '+':
            # Match addition, avoid unary plus
            matches = re.findall(r'[\w\)\]]\s*\+\s*[\w\(\[]', line)
            counts[counter] += len(matches)
        elif op == '/':
            # Avoid comment //
            matches = re.findall(r'[\w\)\]]\s*/\s*[\w\(\[]', line)
            # Double check it's not a comment
            counts[counter] += len([m for m in matches if '//' not in m])
    
    return counts


def count_math_functions(line: str) -> dict:
    """Count math function calls in a line of code."""
    counts = {v: 0 for v in set(MATH_FUNCTIONS.values())}
    
    # Skip comments
    if line.strip().startswith('//'):
        return counts
    
    for func, counter in MATH_FUNCTIONS.items():
        # Match function calls: funcname(
        pattern = rf'\b{func}\s*\('
        matches = re.findall(pattern, line)
        counts[counter] += len(matches)
    
    return counts


def instrument_line(line: str, line_counts: dict) -> str:
    """Generate counter increment statements for a line's operations."""
    increments = []
    for counter, count in line_counts.items():
        if count > 0:
            increments.append(f'g_arith_profile.{counter} += {count};')
    return increments


def extract_includes(content: str) -> str:
    """Extract #include statements from the original file."""
    includes = []
    for line in content.split('\n'):
        stripped = line.strip()
        # Match #include statements, but skip <cstdint> and <iostream> as they're already in header
        if stripped.startswith('#include'):
            if '<cstdint>' not in stripped and '<iostream>' not in stripped:
                includes.append(stripped)
    return '\n'.join(includes)


def find_run_test_kernel(content: str) -> tuple:
    """Find the run_test_kernel function and return its bounds."""
    # Pattern to match function definition
    pattern = r'void\s+\w+::run_test_kernel\s*\([^)]*\)\s*\{'
    match = re.search(pattern, content)
    
    if not match:
        return None, None, None
    
    start = match.start()
    func_start = match.end()
    
    # Find matching closing brace
    brace_count = 1
    pos = func_start
    while pos < len(content) and brace_count > 0:
        if content[pos] == '{':
            brace_count += 1
        elif content[pos] == '}':
            brace_count -= 1
        pos += 1
    
    return start, func_start, pos


def extract_function_body(content: str, start: int, end: int) -> str:
    """Extract and return the function body between braces."""
    return content[start:end-1]  # Exclude the closing brace


def instrument_function_body(body: str) -> str:
    """Instrument the function body with arithmetic operation counters."""
    lines = body.split('\n')
    instrumented_lines = []
    
    # Add reset at the beginning
    instrumented_lines.append('\n    // Reset arithmetic profile counters')
    instrumented_lines.append('    g_arith_profile.reset();')
    
    for line in lines:
        # Count operations in this line
        binary_counts = count_binary_ops(line)
        func_counts = count_math_functions(line)
        
        # Merge counts
        all_counts = {**binary_counts, **func_counts}
        
        # Generate increment statements
        increments = instrument_line(line, all_counts)
        
        # Add increment statements before the line (if any)
        for inc in increments:
            # Match indentation of original line
            indent = len(line) - len(line.lstrip())
            instrumented_lines.append(' ' * indent + inc)
        
        # Add the original line
        instrumented_lines.append(line)
    
    # Add print at the end
    instrumented_lines.append('')
    instrumented_lines.append('    // Print arithmetic profile results')
    instrumented_lines.append('    g_arith_profile.print();')
    
    return '\n'.join(instrumented_lines)


def extract_other_functions(content: str, test_kernel_start: int, test_kernel_end: int) -> list:
    """Extract other kernel functions (cpu, gpu, fpga) from the original file."""
    functions = []
    
    # Patterns for other functions
    patterns = [
        r'void\s+(\w+)::run_cpu_kernel\s*\([^)]*\)\s*\{',
        r'void\s+(\w+)::run_gpu_kernel\s*\([^)]*\)\s*\{',
        r'void\s+(\w+)::run_fpga_kernel\s*\([^)]*\)\s*\{',
    ]
    
    for pattern in patterns:
        for match in re.finditer(pattern, content):
            func_start = match.start()
            body_start = match.end()
            
            # Skip if this overlaps with run_test_kernel
            if test_kernel_start <= func_start < test_kernel_end:
                continue
            
            # Find matching closing brace
            brace_count = 1
            pos = body_start
            while pos < len(content) and brace_count > 0:
                if content[pos] == '{':
                    brace_count += 1
                elif content[pos] == '}':
                    brace_count -= 1
                pos += 1
            
            functions.append(content[func_start:pos])
    
    return functions


def generate_profile_file(input_path: str, output_path: str = None) -> str:
    """Generate a profiled version of the input kernel file."""
    input_path = Path(input_path)
    
    if output_path is None:
        output_path = input_path.parent / f"{input_path.stem}_profile.cpp"
    else:
        output_path = Path(output_path)
    
    # Read input file
    with open(input_path, 'r') as f:
        content = f.read()
    
    # Extract includes from original file
    includes = extract_includes(content)
    
    # Find run_test_kernel function
    func_def_start, func_body_start, func_end = find_run_test_kernel(content)
    
    if func_def_start is None:
        print(f"Error: Could not find run_test_kernel function in {input_path}")
        sys.exit(1)
    
    # Extract function signature (for reconstruction)
    func_signature = content[func_def_start:func_body_start]
    
    # Extract and instrument the function body
    func_body = extract_function_body(content, func_body_start, func_end)
    instrumented_body = instrument_function_body(func_body)
    
    # Extract other functions
    other_functions = extract_other_functions(content, func_def_start, func_end)
    
    # Generate output
    output = PROFILE_HEADER.format(filename=output_path.name, includes=includes)
    output += func_signature
    output += instrumented_body
    output += '\n}\n'
    
    # Add other functions
    for func in other_functions:
        output += '\n' + func + '\n'
    
    output += PROFILE_FOOTER
    
    # Write output file
    with open(output_path, 'w') as f:
        f.write(output)
    
    print(f"Generated: {output_path}")
    return str(output_path)


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        sys.exit(1)
    
    input_file = sys.argv[1]
    output_file = sys.argv[2] if len(sys.argv) > 2 else None
    
    generate_profile_file(input_file, output_file)


if __name__ == '__main__':
    main()
